# Generated by Django 2.2.16 on 2020-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='degree',
            field=models.CharField(blank=True, choices=[('本科', '本科'), (1, '硕士'), (2, '博士')], max_length=135, verbose_name='学历'),
        ),
    ]
