# Generated by Django 2.2.16 on 2020-11-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201118_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='degree',
            field=models.SmallIntegerField(blank=True, choices=[(0, '本科'), (1, '硕士'), (3, '博士')], max_length=135, verbose_name='学历'),
        ),
    ]
