# Generated by Django 2.2.16 on 2020-11-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', '导出候选人列表'), ('notify', '通知面试官面试')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
    ]
